# Project: Laberinto
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = juego.o
LINKOBJ  = juego.o
LIBS     = -L"C:/Utilidades/Devc++/Dev-Cpp/MinGW64/lib" -L"C:/Utilidades/Devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Utilidades/Devc++/Dev-Cpp/MinGW64/include" -I"C:/Utilidades/Devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Utilidades/Devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Utilidades/Devc++/Dev-Cpp/MinGW64/include" -I"C:/Utilidades/Devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Utilidades/Devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Utilidades/Devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Laberinto.exe
CXXFLAGS = $(CXXINCS) -Ofast -std=gnu++11 -g3
CFLAGS   = $(INCS) -Ofast -std=gnu++11 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

juego.o: juego.cpp
	$(CPP) -c juego.cpp -o juego.o $(CXXFLAGS)
